[package]
name = "mysql-connector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


toml
[dependencies]
serde = "1.0"
serde_json = "1.0"
kafka-rust = "0.25"
mysql-async = "0.20"