version: '3'

services:
  zookeeper:
    image: debezium/zookeeper:1.7
    ports:
      - "2181:2181"

  kafka:
    image: debezium/kafka:1.7
    ports:
      - "9092:9092"
    links:
      - zookeeper

  mysql:
    image: debezium/example-mysql:1.7
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=mydb
    ports:
      - "3306:3306"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - debezium-network

  dozer-samples:
    # Your Rust-based connector image goes here
    image: your-dozer-connector-image:latest
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_DATABASE=mydb
    networks:
      - debezium-network

networks:
  debezium-network:
    driver: bridge