[workspace]
members = [
  "dozer-api",
  "dozer-ingestion",
  "dozer-types",
  "dozer-storage",
  "dozer-core",
  "dozer-cli",
  "dozer-sql",
  "dozer-cache",
  "dozer-tracing",
  "dozer-tests",
  "dozer-log",
  "dozer-log-js",
  "dozer-log-python",
  "dozer-utils"
]

[patch.crates-io]
postgres = { git = "https://github.com/getdozer/rust-postgres" }
postgres-protocol = { git = "https://github.com/getdozer/rust-postgres" }
postgres-types = { git = "https://github.com/getdozer/rust-postgres" }
tokio-postgres = { git = "https://github.com/getdozer/rust-postgres" }
[dependencies]
mysql_async = "0.28.0"
tokio = { version = "1.14.0", features = ["full"] }